# Header
menu:
  Home: /
  Archives: /archives
#rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true #false
mathjax: false

# Sidebar
sidebar: bottom #right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts
- links

# widget behavior
archive_type: 'monthly'
show_count: true

# Links
links:
  # 主题作者: http://arvinxiang.com

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins: 
fb_app_id:

# Duoshuo
# duoshuo_shortname: 

# Baidu share
baidushare: true